### ISSUE TITLE
rad value conversion 

### ISSUE THREAD

**Issue by jakob-e** [xi/sass-planifolia#1]
@xi thanks for sharing your fast compiling math functions – very impressive results :-)
To speed up and simplify to-rad-value – consider using native fixed unit conversion:

````SCSS
//  convert to rad and strip unit 
@function rad-value($x){ 
    @return (0rad + $x)/1rad; 
}

.x {
    num : rad-value(4.71239);    
    rad : rad-value(4.71239rad);    
    deg : rad-value(270deg);
    turn: rad-value(.75turn);
    grad: rad-value(300grad); 
}
``````
``````CSS
.x {
  num:  4.71239;
  rad:  4.71239;
  deg:  4.71239;
  turn: 4.71239;
  grad: 4.71239;
}
